name: schedule_dbt_job

on:
  push:
    branches:
    # run on push to development branch
    - main
env:
  DBT_PROFILES_DIR: ./

DBT_SNOWFLAKE_USERNAME: "NROY"
DBT_SNOWFLAKE_PW: "Pass1234"
DBT_SNOWFLAKE_ROLE: "SYSADMIN"

jobs:
  schedule_dbt_job:
    name: schedule_dbt_job
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@main

      - uses: actions/setup-python@v1
        with:
          python-version: "3.7.x"

      - name: Install dependencies
        run: |
          pip install dbt
          dbt deps --target prod
      
      # Add dbt seed or other commands here if needed
      - name: Run dbt models
        run: dbt run

      - name: Test dbt models
        run: dbt test
